//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.19 at 09:54:55 AM NPT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://mp.com/spring-boot-soap", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mp.spring_boot_soap;
